name: Check code formatting

on:
  pull_request:

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.14.0.0"
