name: Check code formatting

on:
  pull_request:

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command fourmolu -m check .
